packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  msgpackr-extract: true
  protobufjs: true

catalog:
  typescript: ^7.0.2
  vitest: ^5.0.1
  "@types/node": ^22.20.4

onlyBuiltDependencies:
  - esbuild
  - "@biomejs/biome"
  - protobufjs
